In [1]:
import os
os.getcwd()

'/home/philipp/deng/deng-ingestion-pipeline/notebooks/raw_checks'

In [6]:
import pandas as pd
from pathlib import Path
from IPython.display import display, Markdown

# ------------------------------------------------------------
# Load raw GDELT export files
# ------------------------------------------------------------
raw_dir = Path("../../data/raw/")
csv_files = sorted(raw_dir.glob("*.export.CSV"))

dfs = []
for file in csv_files:
    df = pd.read_csv(file, sep="\t", header=None)
    df["_source_file"] = file.name   # temporary extra column
    dfs.append(df)

df_all = pd.concat(dfs, ignore_index=True)

print(f"Rows: {df_all.shape[0]}, Columns: {df_all.shape[1]}")
display(df_all.head())

# ------------------------------------------------------------
# Define GDELT Event table headers
# ------------------------------------------------------------
event_columns = [
    "GlobalEventID",
    "Day",
    "MonthYear",
    "Year",
    "FractionDate",

    "Actor1Code",
    "Actor1Name",
    "Actor1CountryCode",
    "Actor1KnownGroupCode",
    "Actor1EthnicCode",
    "Actor1Religion1Code",
    "Actor1Religion2Code",
    "Actor1Type1Code",
    "Actor1Type2Code",
    "Actor1Type3Code",

    "Actor2Code",
    "Actor2Name",
    "Actor2CountryCode",
    "Actor2KnownGroupCode",
    "Actor2EthnicCode",
    "Actor2Religion1Code",
    "Actor2Religion2Code",
    "Actor2Type1Code",
    "Actor2Type2Code",
    "Actor2Type3Code",

    "IsRootEvent",
    "EventCode",
    "EventBaseCode",
    "EventRootCode",
    "QuadClass",
    "GoldsteinScale",
    "NumMentions",
    "NumSources",
    "NumArticles",
    "AvgTone",

    "Actor1Geo_Type",
    "Actor1Geo_Fullname",
    "Actor1Geo_CountryCode",
    "Actor1Geo_ADM1Code",
    "Actor1Geo_ADM2Code",
    "Actor1Geo_Lat",
    "Actor1Geo_Long",
    "Actor1Geo_FeatureID",

    "Actor2Geo_Type",
    "Actor2Geo_Fullname",
    "Actor2Geo_CountryCode",
    "Actor2Geo_ADM1Code",
    "Actor2Geo_ADM2Code",
    "Actor2Geo_Lat",
    "Actor2Geo_Long",
    "Actor2Geo_FeatureID",

    "ActionGeo_Type",
    "ActionGeo_Fullname",
    "ActionGeo_CountryCode",
    "ActionGeo_ADM1Code",
    "ActionGeo_ADM2Code",
    "ActionGeo_Lat",
    "ActionGeo_Long",
    "ActionGeo_FeatureID",

    "DATEADDED",
    "SOURCEURL",
]

source_file_col = df_all["_source_file"]
df_events = df_all.drop(columns=["_source_file"])

if df_events.shape[1] != len(event_columns):
    raise ValueError(
        f"Column count mismatch: dataframe has {df_events.shape[1]} columns, "
        f"but header list contains {len(event_columns)} columns."
    )

df_events.columns = event_columns
df_events["source_file"] = source_file_col

print(f"Rows: {df_events.shape[0]}, Columns: {df_events.shape[1]}")
display(df_events.head())

Rows: 1110273, Columns: 62

,0,1,2,3,4,5,6,7,8,9,...,52,53,54,55,56,57,58,59,60,_source_file
0,1292303805,20250304,202503,2025,2025.1753,NaN,NaN,NaN,NaN,NaN,...,"Alicante, Valenciana, Spain",SP,SP60,25811,38.3462,-0.487722,-370210,20260304101500,https://www.thelocal.es/20260304/today-in-spai...,20260304101500.export.CSV
1,1292303806,20250304,202503,2025,2025.1753,NaN,NaN,NaN,NaN,NaN,...,"Belfast, Belfast, United Kingdom",UK,UKR3,40158,54.5833,-5.933330,-2589607,20260304101500,https://www.belfastlive.co.uk/news/northern-ir...,20260304101500.export.CSV
2,1292303807,20250304,202503,2025,2025.1753,NaN,NaN,NaN,NaN,NaN,...,"Torrevieja, Valenciana, Spain",SP,SP60,25811,37.9787,-0.682222,-404832,20260304101500,https://www.belfastlive.co.uk/news/northern-ir...,20260304101500.export.CSV
3,1292303808,20250304,202503,2025,2025.1753,NaN,NaN,NaN,NaN,NaN,...,"Belfast, Belfast, United Kingdom",UK,UKR3,40158,54.5833,-5.933330,-2589607,20260304101500,https://www.belfastlive.co.uk/news/northern-ir...,20260304101500.export.CSV
4,1292303809,20250304,202503,2025,2025.1753,NaN,NaN,NaN,NaN,NaN,...,"Torrevieja, Valenciana, Spain",SP,SP60,25811,37.9787,-0.682222,-404832,20260304101500,https://www.dailystar.co.uk/news/world-news/jo...,20260304101500.export.CSV

Rows: 1110273, Columns: 62

,GlobalEventID,Day,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,...,ActionGeo_Fullname,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL,source_file
0,1292303805,20250304,202503,2025,2025.1753,NaN,NaN,NaN,NaN,NaN,...,"Alicante, Valenciana, Spain",SP,SP60,25811,38.3462,-0.487722,-370210,20260304101500,https://www.thelocal.es/20260304/today-in-spai...,20260304101500.export.CSV
1,1292303806,20250304,202503,2025,2025.1753,NaN,NaN,NaN,NaN,NaN,...,"Belfast, Belfast, United Kingdom",UK,UKR3,40158,54.5833,-5.933330,-2589607,20260304101500,https://www.belfastlive.co.uk/news/northern-ir...,20260304101500.export.CSV
2,1292303807,20250304,202503,2025,2025.1753,NaN,NaN,NaN,NaN,NaN,...,"Torrevieja, Valenciana, Spain",SP,SP60,25811,37.9787,-0.682222,-404832,20260304101500,https://www.belfastlive.co.uk/news/northern-ir...,20260304101500.export.CSV
3,1292303808,20250304,202503,2025,2025.1753,NaN,NaN,NaN,NaN,NaN,...,"Belfast, Belfast, United Kingdom",UK,UKR3,40158,54.5833,-5.933330,-2589607,20260304101500,https://www.belfastlive.co.uk/news/northern-ir...,20260304101500.export.CSV
4,1292303809,20250304,202503,2025,2025.1753,NaN,NaN,NaN,NaN,NaN,...,"Torrevieja, Valenciana, Spain",SP,SP60,25811,37.9787,-0.682222,-404832,20260304101500,https://www.dailystar.co.uk/news/world-news/jo...,20260304101500.export.CSV

In [7]:
from IPython.display import display, Markdown

chapters = {
    "EventID and Date {5 | 0-4}": [
        "GlobalEventID",
        "Day",
        "MonthYear",
        "Year",
        "FractionDate",
    ],
    "Actor (Actor 1 Action performed) {10 | 5-14}": [
        "Actor1Code",
        "Actor1Name",
        "Actor1CountryCode",
        "Actor1KnownGroupCode",
        "Actor1EthnicCode",
        "Actor1Religion1Code",
        "Actor1Religion2Code",
        "Actor1Type1Code",
        "Actor1Type2Code",
        "Actor1Type3Code",
    ],
    'Actor (Actor 2 "received" Action) {10 | 15-24}': [
        "Actor2Code",
        "Actor2Name",
        "Actor2CountryCode",
        "Actor2KnownGroupCode",
        "Actor2EthnicCode",
        "Actor2Religion1Code",
        "Actor2Religion2Code",
        "Actor2Type1Code",
        "Actor2Type2Code",
        "Actor2Type3Code",
    ],
    "Event Action Attributes {10 | 25-34}": [
        "IsRootEvent",
        "EventCode",
        "EventBaseCode",
        "EventRootCode",
        "QuadClass",
        "GoldsteinScale",
        "NumMentions",
        "NumSources",
        "NumArticles",
        "AvgTone",
    ],
    "Event Geography Actor 1 {8 | 35-42}": [
        "Actor1Geo_Type",
        "Actor1Geo_Fullname",
        "Actor1Geo_CountryCode",
        "Actor1Geo_ADM1Code",
        "Actor1Geo_ADM2Code",
        "Actor1Geo_Lat",
        "Actor1Geo_Long",
        "Actor1Geo_FeatureID",
    ],
    "Event Geography Actor 2 {8 | 43-50}": [
        "Actor2Geo_Type",
        "Actor2Geo_Fullname",
        "Actor2Geo_CountryCode",
        "Actor2Geo_ADM1Code",
        "Actor2Geo_ADM2Code",
        "Actor2Geo_Lat",
        "Actor2Geo_Long",
        "Actor2Geo_FeatureID",
    ],
    "Event Geography Action {8 | 51-58}": [
        "ActionGeo_Type",
        "ActionGeo_Fullname",
        "ActionGeo_CountryCode",
        "ActionGeo_ADM1Code",
        "ActionGeo_ADM2Code",
        "ActionGeo_Lat",
        "ActionGeo_Long",
        "ActionGeo_FeatureID",
    ],
    "Data Management Fields {2 | 59-60}": [
        "DATEADDED",
        "SOURCEURL",
    ],
}
for chapter_name, chapter_columns in chapters.items():
    display(Markdown(f"## {chapter_name}"))
    display(df_events[chapter_columns].head())

## EventID and Date {5 | 0-4}

   GlobalEventID       Day  MonthYear  Year  FractionDate
0     1292303805  20250304     202503  2025     2025.1753
1     1292303806  20250304     202503  2025     2025.1753
2     1292303807  20250304     202503  2025     2025.1753
3     1292303808  20250304     202503  2025     2025.1753
4     1292303809  20250304     202503  2025     2025.1753

## Actor (Actor 1 Action performed) {10 | 5-14}

,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,Actor1Religion1Code,Actor1Religion2Code,Actor1Type1Code,Actor1Type2Code,Actor1Type3Code
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Actor (Actor 2 "received" Action) {10 | 15-24}

,Actor2Code,Actor2Name,Actor2CountryCode,Actor2KnownGroupCode,Actor2EthnicCode,Actor2Religion1Code,Actor2Religion2Code,Actor2Type1Code,Actor2Type2Code,Actor2Type3Code
0,ESP,SPANIARD,ESP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IRL,IRELAND,IRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IRL,IRISHMAN,IRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IRL,IRELAND,IRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IRL,IRELAND,IRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Event Action Attributes {10 | 25-34}

,IsRootEvent,EventCode,EventBaseCode,EventRootCode,QuadClass,GoldsteinScale,NumMentions,NumSources,NumArticles,AvgTone
0,1,60,60,6,2,6.0,8,1,8,-2.422907
1,0,172,172,17,4,-5.0,1,1,1,-7.744108
2,0,172,172,17,4,-5.0,3,1,3,-7.744108
3,0,190,190,19,4,-10.0,2,2,2,-7.929197
4,1,190,190,19,4,-10.0,2,1,2,-8.114286

## Event Geography Actor 1 {8 | 35-42}

,Actor1Geo_Type,Actor1Geo_Fullname,Actor1Geo_CountryCode,Actor1Geo_ADM1Code,Actor1Geo_ADM2Code,Actor1Geo_Lat,Actor1Geo_Long,Actor1Geo_FeatureID
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Event Geography Actor 2 {8 | 43-50}

,Actor2Geo_Type,Actor2Geo_Fullname,Actor2Geo_CountryCode,Actor2Geo_ADM1Code,Actor2Geo_ADM2Code,Actor2Geo_Lat,Actor2Geo_Long,Actor2Geo_FeatureID
0,4,"Alicante, Valenciana, Spain",SP,SP60,25811,38.3462,-0.487722,-370210
1,4,"Belfast, Belfast, United Kingdom",UK,UKR3,40158,54.5833,-5.933330,-2589607
2,1,Ireland,EI,EI,NaN,53.0000,-8.000000,EI
3,4,"Belfast, Belfast, United Kingdom",UK,UKR3,40158,54.5833,-5.933330,-2589607
4,4,"Torrevieja, Valenciana, Spain",SP,SP60,25811,37.9787,-0.682222,-404832

## Event Geography Action {8 | 51-58}

,ActionGeo_Type,ActionGeo_Fullname,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID
0,4,"Alicante, Valenciana, Spain",SP,SP60,25811,38.3462,-0.487722,-370210
1,4,"Belfast, Belfast, United Kingdom",UK,UKR3,40158,54.5833,-5.933330,-2589607
2,4,"Torrevieja, Valenciana, Spain",SP,SP60,25811,37.9787,-0.682222,-404832
3,4,"Belfast, Belfast, United Kingdom",UK,UKR3,40158,54.5833,-5.933330,-2589607
4,4,"Torrevieja, Valenciana, Spain",SP,SP60,25811,37.9787,-0.682222,-404832

## Data Management Fields {2 | 59-60}

        DATEADDED                                          SOURCEURL
0  20260304101500  https://www.thelocal.es/20260304/today-in-spai...
1  20260304101500  https://www.belfastlive.co.uk/news/northern-ir...
2  20260304101500  https://www.belfastlive.co.uk/news/northern-ir...
3  20260304101500  https://www.belfastlive.co.uk/news/northern-ir...
4  20260304101500  https://www.dailystar.co.uk/news/world-news/jo...

In [8]:
import pandas as pd

columns_to_check = [
    "GlobalEventID",
    "Day",
    "MonthYear",
    "Year",
    "FractionDate",
    "QuadClass",
    "GoldsteinScale",
    "NumMentions",
    "NumSources",
    "NumArticles",
    "AvgTone",
    "Actor1Geo_Type",
    "Actor1Geo_Lat",
    "Actor1Geo_Long",
    "Actor2Geo_Type",
    "Actor2Geo_Lat",
    "Actor2Geo_Long",
    "ActionGeo_Type",
    "ActionGeo_Lat",
    "ActionGeo_Long"  
]

for col in columns_to_check:
    series = df_events[col].dropna().astype(str).str.strip()
    series = series[series != ""]

    decimal_lengths = series.apply(
        lambda x: len(x.split(".")[1]) if "." in x else 0
    )

    print("=" * 80)
    print(f"Column: {col}")
    print(f"Non-empty rows: {len(series)}")

    print("\nSample values:")
    print(series.drop_duplicates().sort_values().head(20).to_list())

    print("\nMin / Max (numeric):")
    numeric_series = pd.to_numeric(series, errors="coerce")
    print(f"Min: {numeric_series.min()}")
    print(f"Max: {numeric_series.max()}")

    print("\nMax decimal places found:")
    print(decimal_lengths.max())

    print("\nDistribution of decimal places:")
    print(decimal_lengths.value_counts().sort_index())

    if (decimal_lengths > 0).any():
        print("\nExamples with decimals:")
        display(series[decimal_lengths > 0].drop_duplicates().sort_values().head(20))

================================================================================
Column: GlobalEventID
Non-empty rows: 1110273

Sample values:
['1292303805', '1292303806', '1292303807', '1292303808', '1292303809', '1292303810', '1292303811', '1292303812', '1292303813', '1292303814', '1292303815', '1292303816', '1292303817', '1292303818', '1292303819', '1292303820', '1292303821', '1292303822', '1292303823', '1292303824']

Min / Max (numeric):
Min: 1292303805
Max: 1296824447

Max decimal places found:
0

Distribution of decimal places:
GlobalEventID
0    1110273
Name: count, dtype: int64
================================================================================
Column: Day
Non-empty rows: 1110273

Sample values:
['20160306', '20160307', '20160308', '20160309', '20160310', '20160311', '20160312', '20160313', '20160314', '20160331', '20160401', '20250304', '20250305', '20250306', '20250307', '20250308', '20250309', '20250310', '20250311', '20250312']

Min / Max (numeric):
Min: 20160306
Max: 20260330

Max decimal places found:
0

Distribution of decimal places:
Day
0    1110273
Name: count, dtype: int64
================================================================================
Column: MonthYear
Non-empty rows: 1110273

Sample values:
['201603', '201604', '202503', '202602', '202603']

Min / Max (numeric):
Min: 201603
Max: 202603

Max decimal places found:
0

Distribution of decimal places:
MonthYear
0    1110273
Name: count, dtype: int64
================================================================================
Column: Year
Non-empty rows: 1110273

Sample values:
['2016', '2025', '2026']

Min / Max (numeric):
Min: 2016
Max: 2026

Max decimal places found:
0

Distribution of decimal places:
Year
0    1110273
Name: count, dtype: int64
================================================================================
Column: FractionDate
Non-empty rows: 1110273

Sample values:
['2016.1808', '2016.1836', '2016.1863', '2016.189', '2016.1918', '2016.1945', '2016.1973', '2016.2', '2016.2027', '2016.2493', '2025.1753', '2025.1781', '2025.1808', '2025.1836', '2025.1863', '2025.189', '2025.1918', '2025.1945', '2025.1973', '2025.2438']

Min / Max (numeric):
Min: 2016.1808
Max: 2026.2466

Max decimal places found:
4

Distribution of decimal places:
FractionDate
1        40
3    115117
4    995116
Name: count, dtype: int64

Examples with decimals:

7992       2016.1808
93444      2016.1836
267042     2016.1863
402409      2016.189
470295     2016.1918
557499     2016.1945
662844     2016.1973
793174        2016.2
928152     2016.2027
1020987    2016.2493
0          2025.1753
85147      2025.1781
235891     2025.1808
373256     2025.1836
465240     2025.1863
543554      2025.189
660310     2025.1918
787082     2025.1945
918638     2025.1973
1014876    2025.2438
Name: FractionDate, dtype: object

================================================================================
Column: QuadClass
Non-empty rows: 1110273

Sample values:
['1', '2', '3', '4']

Min / Max (numeric):
Min: 1
Max: 4

Max decimal places found:
0

Distribution of decimal places:
QuadClass
0    1110273
Name: count, dtype: int64
================================================================================
Column: GoldsteinScale
Non-empty rows: 1110269

Sample values:
['-0.1', '-0.3', '-0.4', '-10.0', '-2.0', '-4.0', '-4.4', '-5.0', '-5.6', '-5.8', '-6.5', '-7.0', '-7.2', '-7.5', '-8.0', '-9.0', '-9.2', '-9.5', '0.0', '0.4']

Min / Max (numeric):
Min: -10.0
Max: 10.0

Max decimal places found:
1

Distribution of decimal places:
GoldsteinScale
1    1110269
Name: count, dtype: int64

Examples with decimals:

945      -0.1
217      -0.3
97       -0.4
3       -10.0
38       -2.0
8        -4.0
37       -4.4
1        -5.0
5753     -5.6
1475     -5.8
35       -6.5
362      -7.0
222      -7.2
1066     -7.5
1469     -8.0
117      -9.0
407      -9.2
83       -9.5
7         0.0
142       0.4
Name: GoldsteinScale, dtype: object

================================================================================
Column: NumMentions
Non-empty rows: 1110273

Sample values:
['1', '10', '100', '102', '104', '105', '106', '108', '11', '110', '112', '1130', '114', '116', '12', '120', '128', '13', '130', '136']

Min / Max (numeric):
Min: 1
Max: 1130

Max decimal places found:
0

Distribution of decimal places:
NumMentions
0    1110273
Name: count, dtype: int64
================================================================================
Column: NumSources
Non-empty rows: 1110273

Sample values:
['1', '10', '11', '12', '13', '14', '15', '16', '17', '2', '20', '22', '3', '4', '5', '6', '7', '8', '9']

Min / Max (numeric):
Min: 1
Max: 22

Max decimal places found:
0

Distribution of decimal places:
NumSources
0    1110273
Name: count, dtype: int64
================================================================================
Column: NumArticles
Non-empty rows: 1110273

Sample values:
['1', '10', '100', '102', '104', '105', '106', '11', '110', '112', '1130', '12', '120', '128', '13', '130', '136', '138', '14', '140']

Min / Max (numeric):
Min: 1
Max: 1130

Max decimal places found:
0

Distribution of decimal places:
NumArticles
0    1110273
Name: count, dtype: int64
================================================================================
Column: AvgTone
Non-empty rows: 1110273

Sample values:
['-0.0011877048790851', '-0.001735433207513', '-0.0032513647175549', '-0.0042980089405833', '-0.0050087653393445', '-0.012172854534395', '-0.01224026830668', '-0.0124212825861501', '-0.0149678191887467', '-0.0169211306102267', '-0.0194686855225201', '-0.021324945521426', '-0.02161227577264', '-0.0236828832894233', '-0.0245634698921299', '-0.0246417469103051', '-0.0258735060802684', '-0.0263134421550252', '-0.0276116134266188', '-0.0277417836913433']

Min / Max (numeric):
Min: -28.9473684210526
Max: 23.728813559322

Max decimal places found:
20

Distribution of decimal places:
AvgTone
1      30160
2       3983
3       2322
4       2080
5       1511
6        993
7       1028
8        296
9         16
10        36
11       199
12      7519
13    119724
14    922288
15     15233
16      2883
18         1
20         1
Name: count, dtype: int64

Examples with decimals:

739041     -0.0011877048790851
808484      -0.001735433207513
314709     -0.0032513647175549
820148     -0.0042980089405833
916520     -0.0050087653393445
712953      -0.012172854534395
59333        -0.01224026830668
1067565    -0.0124212825861501
953776     -0.0149678191887467
874311     -0.0169211306102267
143883     -0.0194686855225201
8775        -0.021324945521426
279649       -0.02161227577264
219116     -0.0236828832894233
187008     -0.0245634698921299
145984     -0.0246417469103051
1062619    -0.0258735060802684
937215     -0.0263134421550252
817527     -0.0276116134266188
789415     -0.0277417836913433
Name: AvgTone, dtype: object

================================================================================
Column: Actor1Geo_Type
Non-empty rows: 1110273

Sample values:
['0', '1', '2', '3', '4', '5']

Min / Max (numeric):
Min: 0
Max: 5

Max decimal places found:
0

Distribution of decimal places:
Actor1Geo_Type
0    1110273
Name: count, dtype: int64
================================================================================
Column: Actor1Geo_Lat
Non-empty rows: 986186

Sample values:
['-0.004165', '-0.033333', '-0.055873', '-0.0632', '-0.066667', '-0.071338', '-0.076014', '-0.077222', '-0.083333', '-0.083536', '-0.098609', '-0.10221', '-0.111338', '-0.133333', '-0.153889', '-0.157778', '-0.166667', '-0.181392', '-0.2', '-0.208582']

Min / Max (numeric):
Min: -85.6221
Max: 80.7333

Max decimal places found:
7

Distribution of decimal places:
Actor1Geo_Lat
1    293871
2     81834
3     42223
4    495643
5     30118
6     42462
7        35
Name: count, dtype: int64

Examples with decimals:

166913     -0.004165
269307     -0.033333
1030321    -0.055873
667937       -0.0632
268281     -0.066667
272112     -0.071338
59527      -0.076014
50779      -0.077222
525006     -0.083333
973167     -0.083536
710006     -0.098609
29873       -0.10221
73557      -0.111338
823250     -0.133333
333210     -0.153889
951371     -0.157778
222305     -0.166667
524792     -0.181392
524779          -0.2
440076     -0.208582
Name: Actor1Geo_Lat, dtype: object

================================================================================
Column: Actor1Geo_Long
Non-empty rows: 986396

Sample values:
['-0.009908', '-0.010375', '-0.011271', '-0.015017', '-0.016667', '-0.025383', '-0.033333', '-0.034844', '-0.036489', '-0.042002', '-0.045916', '-0.047462', '-0.0498', '-0.05', '-0.050217', '-0.066667', '-0.067337', '-0.076175', '-0.077133', '-0.077913']

Min / Max (numeric):
Min: -179.533
Max: 180.0

Max decimal places found:
7

Distribution of decimal places:
Actor1Geo_Long
1    248970
2     69690
3    138180
4    443760
5     50605
6     35156
7        35
Name: count, dtype: int64

Examples with decimals:

717260    -0.009908
151361    -0.010375
962536    -0.011271
729929    -0.015017
38249     -0.016667
980287    -0.025383
134230    -0.033333
220456    -0.034844
47467     -0.036489
761704    -0.042002
496459    -0.045916
537728    -0.047462
962535      -0.0498
144582        -0.05
837243    -0.050217
398397    -0.066667
622421    -0.067337
40743     -0.076175
55717     -0.077133
874615    -0.077913
Name: Actor1Geo_Long, dtype: object

================================================================================
Column: Actor2Geo_Type
Non-empty rows: 1110273

Sample values:
['0', '1', '2', '3', '4', '5']

Min / Max (numeric):
Min: 0
Max: 5

Max decimal places found:
0

Distribution of decimal places:
Actor2Geo_Type
0    1110273
Name: count, dtype: int64
================================================================================
Column: Actor2Geo_Lat
Non-empty rows: 787476

Sample values:
['-0.004165', '-0.033333', '-0.055873', '-0.066667', '-0.071338', '-0.076014', '-0.077222', '-0.083333', '-0.098609', '-0.1', '-0.10221', '-0.133333', '-0.153889', '-0.157778', '-0.166667', '-0.181392', '-0.183333', '-0.2', '-0.208582', '-0.216667']

Min / Max (numeric):
Min: -85.6221
Max: 80.7333

Max decimal places found:
7

Distribution of decimal places:
Actor2Geo_Lat
1    245270
2     68611
3     32066
4    382831
5     22909
6     35772
7        17
Name: count, dtype: int64

Examples with decimals:

165970     -0.004165
268957     -0.033333
1030051    -0.055873
268301     -0.066667
272452     -0.071338
353002     -0.076014
50779      -0.077222
524475     -0.083333
709075     -0.098609
701787          -0.1
126366      -0.10221
822953     -0.133333
333210     -0.153889
951374     -0.157778
222305     -0.166667
524488     -0.181392
966661     -0.183333
524850          -0.2
440076     -0.208582
14564      -0.216667
Name: Actor2Geo_Lat, dtype: object

================================================================================
Column: Actor2Geo_Long
Non-empty rows: 787636

Sample values:
['-0.009908', '-0.010375', '-0.011271', '-0.015017', '-0.016667', '-0.033333', '-0.036489', '-0.042002', '-0.045916', '-0.047462', '-0.0498', '-0.05', '-0.050217', '-0.066667', '-0.067337', '-0.076175', '-0.077133', '-0.077913', '-0.083333', '-0.084376']

Min / Max (numeric):
Min: -178.783
Max: 180.0

Max decimal places found:
7

Distribution of decimal places:
Actor2Geo_Long
1    206029
2     56930
3    101555
4    357162
5     37799
6     28144
7        17
Name: count, dtype: int64

Examples with decimals:

302547    -0.009908
161530    -0.010375
980403    -0.011271
729609    -0.015017
37108     -0.016667
133910    -0.033333
48078     -0.036489
761704    -0.042002
496237    -0.045916
537464    -0.047462
962540      -0.0498
144999        -0.05
836847    -0.050217
19997     -0.066667
622699    -0.067337
190985    -0.076175
55761     -0.077133
874918    -0.077913
9671      -0.083333
49        -0.084376
Name: Actor2Geo_Long, dtype: object

================================================================================
Column: ActionGeo_Type
Non-empty rows: 1110273

Sample values:
['0', '1', '2', '3', '4', '5']

Min / Max (numeric):
Min: 0
Max: 5

Max decimal places found:
0

Distribution of decimal places:
ActionGeo_Type
0    1110273
Name: count, dtype: int64
================================================================================
Column: ActionGeo_Lat
Non-empty rows: 1082186

Sample values:
['-0.004165', '-0.033333', '-0.055873', '-0.0632', '-0.066667', '-0.071338', '-0.076014', '-0.077222', '-0.083333', '-0.083536', '-0.098609', '-0.1', '-0.10221', '-0.111338', '-0.133333', '-0.153889', '-0.157778', '-0.166667', '-0.181392', '-0.183333']

Min / Max (numeric):
Min: -85.6221
Max: 80.7333

Max decimal places found:
7

Distribution of decimal places:
ActionGeo_Lat
1    316203
2     89163
3     47344
4    550992
5     33106
6     45341
7        37
Name: count, dtype: int64

Examples with decimals:

165970     -0.004165
268957     -0.033333
1030051    -0.055873
667937       -0.0632
268281     -0.066667
272112     -0.071338
59527      -0.076014
50779      -0.077222
524475     -0.083333
973168     -0.083536
709075     -0.098609
701787          -0.1
29873       -0.10221
73010      -0.111338
822953     -0.133333
333210     -0.153889
951371     -0.157778
222305     -0.166667
524488     -0.181392
966661     -0.183333
Name: ActionGeo_Lat, dtype: object

================================================================================
Column: ActionGeo_Long
Non-empty rows: 1082438

Sample values:
['-0.009908', '-0.010375', '-0.011271', '-0.015017', '-0.016667', '-0.025383', '-0.033333', '-0.034844', '-0.036489', '-0.042002', '-0.045916', '-0.047462', '-0.0498', '-0.05', '-0.050217', '-0.066667', '-0.067337', '-0.076175', '-0.077133', '-0.077913']

Min / Max (numeric):
Min: -179.533
Max: 180.0

Max decimal places found:
7

Distribution of decimal places:
ActionGeo_Long
1    268935
2     75574
3    155902
4    487730
5     56385
6     37875
7        37
Name: count, dtype: int64

Examples with decimals:

302547    -0.009908
151361    -0.010375
980385    -0.011271
729609    -0.015017
37108     -0.016667
980287    -0.025383
133910    -0.033333
220456    -0.034844
46986     -0.036489
761704    -0.042002
496237    -0.045916
537464    -0.047462
962535      -0.0498
144582        -0.05
836850    -0.050217
19997     -0.066667
622421    -0.067337
40743     -0.076175
55717     -0.077133
874615    -0.077913
Name: ActionGeo_Long, dtype: object